%global packname  CAMERA
%global rlibdir  %{_libdir}/R/library


Name:             R-%{packname}
Version:          1.10.0
Release:          1%{?dist}
Summary:          Collection of annotation related methods for mass spectrometry data

Group:            Applications/Engineering 
License:          GPL (>= 2)
URL:              http://bioconductor.org/packages/release/bioc/html/%{packname}.html
Source0:          http://bioconductor.org/packages/release/bioc/src/contrib/%{packname}_%{version}.tar.gz
BuildRoot:        %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)

Requires:         R-methods R-xcms 
Requires:         R-methods R-xcms R-RBGL R-graph R-graphics R-grDevices R-stats R-utils R-Hmisc R-igraph 

BuildRequires:    R-devel tex(latex) R-methods R-xcms
BuildRequires:    R-methods R-xcms R-RBGL R-graph R-graphics R-grDevices R-stats R-utils R-Hmisc R-igraph 


%description
Annotation of peaklists generated by xcms, rule based annotation of
isotopes and adducts, EIC correlation based tagging of unknown adducts and

%prep
%setup -q -c -n %{packname}

%build

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}%{rlibdir}
%{_bindir}/R CMD INSTALL -l %{buildroot}%{rlibdir} %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)
rm -f %{buildroot}%{rlibdir}/R.css

%clean
rm -rf %{buildroot}

%files
%defattr(-, root, root, -)
%changelog
* Fri Dec 09 2011 Pierre-Yves Chibon <pingou@pingoured.fr> 1.10.0-1
- initial package for Fedora