%global packname  cycle
%global rlibdir  %{_libdir}/R/library


Name:             R-%{packname}
Version:          1.8.0
Release:          1%{?dist}
Summary:          Significance of periodic expression pattern in time-series data

Group:            Applications/Engineering 
License:          GPL-2
URL:              http://bioconductor.org/packages/release/bioc/html/%{packname}.html
Source0:          http://bioconductor.org/packages/release/bioc/src/contrib/%{packname}_%{version}.tar.gz
BuildRoot:        %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)

Requires:         R-Mfuzz 
Requires:         R-Biobase R-stats 

BuildRequires:    R-devel tex(latex) R-Mfuzz
BuildRequires:    R-Biobase R-stats 


%description
Package for assessing the statistical significance of periodic expression
based on Fourier analysis and comparison with data generated by different
background models

%prep
%setup -q -c -n %{packname}

%build

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}%{rlibdir}
%{_bindir}/R CMD INSTALL -l %{buildroot}%{rlibdir} %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)
rm -f %{buildroot}%{rlibdir}/R.css

%clean
rm -rf %{buildroot}

%files
%defattr(-, root, root, -)
%doc %{rlibdir}/cycle/doc
%doc %{rlibdir}/cycle/html
%doc %{rlibdir}/cycle/DESCRIPTION
%{rlibdir}/cycle/NAMESPACE
%{rlibdir}/cycle/INDEX
%{rlibdir}/cycle/R
%{rlibdir}/cycle/help
%{rlibdir}/cycle/Meta

%changelog
* Fri Dec 09 2011 Pierre-Yves Chibon <pingou@pingoured.fr> 1.8.0-1
- initial package for Fedora