%global packname  doRNG
%global rlibdir  %{_datadir}/R/library


Name:             R-%{packname}
Version:          1.0.2
Release:          1%{?dist}
Summary:          Generic Reproducible Parallel Backend for foreach Loops

Group:            Applications/Engineering 
License:          GPL (>= 2)
URL:              http://cran.r-project.org/web/packages/%{packname}/index.html
Source0:          http://cran.r-project.org/src/contrib/%{packname}_%{version}.tar.gz
BuildRoot:        %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:        noarch
Requires:         R-core

Requires:         R-methods R-stats R-foreach R-rstream 

BuildRequires:    R-devel tex(latex) R-methods R-stats R-foreach R-rstream 

%description
This package provides functions to perform reproducible parallel foreach
loops, using independent random streams as generated by the package
rstream. It enables to easily convert standard %dopar% loops into fully
reproducible loops, independently of the number of workers, the task
scheduling strategy, or the chosen parallel environment and associated
foreach backend.

%prep
%setup -q -c -n %{packname}

%build

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}%{rlibdir}
%{_bindir}/R CMD INSTALL -l %{buildroot}%{rlibdir} %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)
rm -f %{buildroot}%{rlibdir}/R.css

%clean
rm -rf %{buildroot}

%files
%defattr(-, root, root, -)
%doc %{rlibdir}/doRNG/html
%doc %{rlibdir}/doRNG/DESCRIPTION
%{rlibdir}/doRNG/NAMESPACE
%{rlibdir}/doRNG/INDEX
%{rlibdir}/doRNG/R
%{rlibdir}/doRNG/help
%{rlibdir}/doRNG/Meta

%changelog
* Thu Nov 24 2011 Pierre-Yves Chibon <pingou@pingoured.fr> 1.0.2-1
- initial package for Fedora