%global packname  ecolMod
%global rlibdir  %{_libdir}/R/library


Name:             R-%{packname}
Version:          1.2.3
Release:          1%{?dist}
Summary:          "A practical guide to ecological modelling - using R as a simulation platform"

Group:            Applications/Engineering 
License:          GPL (>= 2)
URL:              http://cran.r-project.org/web/packages/%{packname}/index.html
Source0:          http://cran.r-project.org/src/contrib/%{packname}_%{version}.tar.gz
BuildRoot:        %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)

Requires:         R-diagram R-rootSolve R-deSolve R-mapdata R-seacarb R-scatterplot3d R-deldir 

BuildRequires:    R-devel tex(latex) R-diagram R-rootSolve R-deSolve R-mapdata R-seacarb R-scatterplot3d R-deldir 

%description
Figures, data sets and examples from the book "A practical guide to
ecological modelling - using R as a simulation platform" by Karline
Soetaert and Peter MJ Herman (2009). Springer. All figures from chapter x
can be generated by "demo(chapx)", where x = 1 to 11. The R-scripts of the
model examples discussed in the book are in subdirectory "examples",
ordered per chapter. Solutions to model projects are in the same

%prep
%setup -q -c -n %{packname}

%build

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}%{rlibdir}
%{_bindir}/R CMD INSTALL -l %{buildroot}%{rlibdir} %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)
rm -f %{buildroot}%{rlibdir}/R.css

%clean
rm -rf %{buildroot}

%files
%defattr(-, root, root, -)
%changelog
* Thu Nov 24 2011 Pierre-Yves Chibon <pingou@pingoured.fr> 1.2.3-1
- initial package for Fedora