%global packname  profr
%global rlibdir  %{_libdir}/R/library


Name:             R-%{packname}
Version:          0.2
Release:          1%{?dist}
Summary:          An alternative display for profiling information

Group:            Applications/Engineering 
License:          MIT
URL:              http://cran.r-project.org/web/packages/%{packname}/index.html
Source0:          http://cran.r-project.org/src/contrib/%{packname}_%{version}.tar.gz
BuildRoot:        %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)


Requires:         R-digest 

BuildRequires:    R-devel tex(latex) 
BuildRequires:    R-digest 


%description
profr provides an alternative data structure and visual rendering for the
profiling information generated by Rprof.

%prep
%setup -q -c -n %{packname}

%build

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}%{rlibdir}
%{_bindir}/R CMD INSTALL -l %{buildroot}%{rlibdir} %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)
rm -f %{buildroot}%{rlibdir}/R.css

%clean
rm -rf %{buildroot}

%files
%defattr(-, root, root, -)
%doc %{rlibdir}/profr/html
%doc %{rlibdir}/profr/NEWS
%doc %{rlibdir}/profr/DESCRIPTION
%{rlibdir}/profr/R
%{rlibdir}/profr/Meta
%{rlibdir}/profr/samples
%{rlibdir}/profr/data
%{rlibdir}/profr/INDEX
%{rlibdir}/profr/help
%{rlibdir}/profr/NAMESPACE

%changelog
* Thu Dec 08 2011 Pierre-Yves Chibon <pingou@pingoured.fr> 0.2-1
- initial package for Fedora